source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods'

IOS_VERSION = '11.0'
platform :ios, IOS_VERSION
plugin 'cocoapods-repo-update'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'tcsdk_selfview_issue' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNTrueConfSdk', podspec: '../node_modules/react-native-trueconf-sdk/ios/RNTrueConfSdk.podspec'
  pod 'react-native-trueconf-react-sdk', podspec: '../node_modules/react-native-trueconf-react-sdk/ios/RNTrueconfReactSdk.podspec', modular_headers: true

  target 'tcsdk_selfview_issueTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'tcsdk_selfview_issue-tvOS' do
  # Pods for tcsdk_selfview_issue-tvOS

  target 'tcsdk_selfview_issue-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  # flipper_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_VERSION
    end
  end

  # rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
  # rnfirebase.build_configurations.each do |config|
  #   config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
  # end

  pod = installer.pods_project.targets.find { |target| target.name == 'react-native-trueconf-react-sdk' }
  pod.build_configurations.each do |config|
    config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/RNTrueConfSdk'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_VERSION
  end
end
